---
version: 2

buildSteps: &buildSteps
  - checkout
  - run:
      name: install-npm
      command: npm install
  - run:
      name: test
      command: npm test

jobs:
  "node-6":
    docker:
      - image: circleci/node:6-browsers
    steps: *buildSteps

  "node-8":
    docker:
      - image: circleci/node:8-browsers
    steps: *buildSteps

workflows:
  version: 2
  build:
    jobs:
      - "node-6"
      - "node-8"
