---
version: 2

buildSteps: &buildSteps
  - checkout
  - run:
      name: install-npm
      command: npm install
  - run:
      name: test
      command: npm test

jobs:
  "node-8":
    docker:
      - image: circleci/node:8-browsers
    steps: *buildSteps

  "node-10":
    docker:
      - image: circleci/node:10-browsers
    steps: *buildSteps

  "node-12":
    docker:
      - image: circleci/node:12-browsers
    steps: *buildSteps

workflows:
  version: 2
  build:
    jobs:
      - "node-8"
      - "node-10"
      - "node-12"
